/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tkalfajr;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class B_Beranda extends javax.swing.JFrame {
    int xx, xy ;

    void dataguru(){
        C_DataGuru A=new C_DataGuru();
       A.setVisible(true);
       dispose();
    }
    
    
    
    
    
    public B_Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bdatasiswa = new javax.swing.JButton();
        bdatakelas = new javax.swing.JButton();
        bdatamapel = new javax.swing.JButton();
        bdatajadwal = new javax.swing.JButton();
        bdatanilai = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bdataguru = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(103, 242, 209));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(103, 242, 209));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        jPanel4.setBackground(new java.awt.Color(103, 242, 209));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        bdatasiswa.setBackground(new java.awt.Color(232, 236, 241));
        bdatasiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdatasiswa.setForeground(new java.awt.Color(36, 37, 42));
        bdatasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_classmates_sittings_skin_type_4_20px.png"))); // NOI18N
        bdatasiswa.setText("Data Murid");
        bdatasiswa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdatasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdatasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatasiswaActionPerformed(evt);
            }
        });

        bdatakelas.setBackground(new java.awt.Color(232, 236, 241));
        bdatakelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdatakelas.setForeground(new java.awt.Color(36, 37, 42));
        bdatakelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_classroom_20px.png"))); // NOI18N
        bdatakelas.setText("Data Kelas");
        bdatakelas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdatakelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdatakelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatakelasActionPerformed(evt);
            }
        });

        bdatamapel.setBackground(new java.awt.Color(232, 236, 241));
        bdatamapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdatamapel.setForeground(new java.awt.Color(36, 37, 42));
        bdatamapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Books_18px.png"))); // NOI18N
        bdatamapel.setText("Data Mapel");
        bdatamapel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdatamapel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdatamapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatamapelActionPerformed(evt);
            }
        });

        bdatajadwal.setBackground(new java.awt.Color(232, 236, 241));
        bdatajadwal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdatajadwal.setForeground(new java.awt.Color(36, 37, 42));
        bdatajadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_planner_19px.png"))); // NOI18N
        bdatajadwal.setText("Data Jadwal");
        bdatajadwal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdatajadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdatajadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatajadwalActionPerformed(evt);
            }
        });

        bdatanilai.setBackground(new java.awt.Color(232, 236, 241));
        bdatanilai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdatanilai.setForeground(new java.awt.Color(36, 37, 42));
        bdatanilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_scorecard_19px.png"))); // NOI18N
        bdatanilai.setText("Data Nilai");
        bdatanilai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdatanilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdatanilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatanilaiActionPerformed(evt);
            }
        });

        btkeluar.setBackground(new java.awt.Color(232, 236, 241));
        btkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkeluar.setForeground(new java.awt.Color(36, 37, 42));
        btkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_export_20px.png"))); // NOI18N
        btkeluar.setText("Keluar");
        btkeluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_conference_110px.png"))); // NOI18N

        bdataguru.setBackground(new java.awt.Color(232, 236, 241));
        bdataguru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdataguru.setForeground(new java.awt.Color(36, 37, 42));
        bdataguru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_coach_20px.png"))); // NOI18N
        bdataguru.setText("Data Guru");
        bdataguru.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdataguru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdataguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataguruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bdatasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdatakelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdatamapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdatanilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdatajadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdataguru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addComponent(bdataguru)
                .addGap(18, 18, 18)
                .addComponent(bdatasiswa)
                .addGap(18, 18, 18)
                .addComponent(bdatakelas)
                .addGap(18, 18, 18)
                .addComponent(bdatamapel)
                .addGap(18, 18, 18)
                .addComponent(bdatajadwal)
                .addGap(18, 18, 18)
                .addComponent(bdatanilai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btkeluar)
                .addGap(33, 33, 33))
        );

        jPanel1.setBackground(new java.awt.Color(197, 239, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_24px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_minimize_window_24px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 222, 39));
        jLabel4.setText("TK Mardiyyatuzziyadah");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 46, 74));
        jLabel5.setText("VISI");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 46, 74));
        jLabel6.setText("MENCERDASKAN GENERASI PENERUS BANGSA YANG DIDASARI IMAN DAN TAQWA KEPADA ALLAH SWT");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 46, 74));
        jLabel7.setText("MISI");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 46, 74));
        jLabel8.setText("BERIMAN DAN BERTAQWA KEPADA ALLAH SWT, BERILMU, BERAKHLAK MULIA, SERTA BERAMAL SHOLEH");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 222, 39));
        jLabel9.setText("Informasi Pendaftaran");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Location_40px_1.png"))); // NOI18N

        jLabel11.setText("JL. Buncit Raya Pulo. 25A 9 RT.10/RW.05");

        jLabel12.setText("Kali Bata, Jakarta Selatan");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo atk.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))))))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(799, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx=  evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void bdataguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataguruActionPerformed
        new C_DataGuru().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdataguruActionPerformed

    private void bdatasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatasiswaActionPerformed
        new D_DataSiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdatasiswaActionPerformed

    private void bdatakelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatakelasActionPerformed
        new E_DataKelas().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdatakelasActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        new A_LoginForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    private void bdatamapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatamapelActionPerformed
        new F_DataMapel().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdatamapelActionPerformed

    private void bdatajadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatajadwalActionPerformed
        new G_DataJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdatajadwalActionPerformed

    private void bdatanilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatanilaiActionPerformed
        new H_DataNilai().setVisible(true);
        dispose();
    }//GEN-LAST:event_bdatanilaiActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdataguru;
    private javax.swing.JButton bdatajadwal;
    private javax.swing.JButton bdatakelas;
    private javax.swing.JButton bdatamapel;
    private javax.swing.JButton bdatanilai;
    private javax.swing.JButton bdatasiswa;
    private javax.swing.JButton btkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
